defaults:
  - base_dataset

train:
  _target_: src.dataset.v1.V1SingleImage
  img_root: "v1/train"
  annotations_path: "v1/train.json"
  shuffle: True

val:
  _target_: src.dataset.v1.V1SingleImage
  img_root: "v1/val"
  annotations_path: "v1/val.json"
